apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrape-elcomercio
  labels:
    app: scrape-elcomercio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrape-elcomercio
  template:
    metadata:
      labels:
        app: scrape-elcomercio
    spec:
      containers:
      - name: scrape-elcomercio
        image: 711442408216.dkr.ecr.us-east-2.amazonaws.com/ttrecordregistry:latest
        command: ["python3", "Elcomercio.py"]
#        args: ["EgressLiveAllCowBehaviorAgg18001.yaml"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "768Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"