apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 711442408216.dkr.ecr.us-east-2.amazonaws.com/api:latest
        ports:
        - containerPort: 5000